--- #YAML:1.0
name:                     Labyrinth::Plugin::Core
version:                  5.06
abstract:                 Labyrinth Website Management Framework Core Plugins
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Labyrinth:              5.03
  Clone:                  0
  Time::Local:            0
  Image::Size:            0
  File::Copy:             0
  File::Basename:         0
  Digest::MD5:            0
  URI::Escape:            0
  Config::IniFiles:       0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
  Test::JSON::Meta:       0.08
build_requires:
  Test::More:             0.01

provides:
  Labyrinth::Plugin::Articles:
    file:     lib/Labyrinth/Plugin/Articles.pm
    version:  5.06
  Labyrinth::Plugin::Articles::Sections:
    file:     lib/Labyrinth/Plugin/Articles/Sections.pm
    version:  5.06
  Labyrinth::Plugin::Articles::Site:
    file:     lib/Labyrinth/Plugin/Articles/Site.pm
    version:  5.06
  Labyrinth::Plugin::Content:
    file:     lib/Labyrinth/Plugin/Content.pm
    version:  5.06
  Labyrinth::Plugin::Core:
    file:     lib/Labyrinth/Plugin/Core.pm
    version:  5.06
  Labyrinth::Plugin::Folders:
    file:     lib/Labyrinth/Plugin/Folders.pm
    version:  5.06
  Labyrinth::Plugin::Groups:
    file:     lib/Labyrinth/Plugin/Groups.pm
    version:  5.06
  Labyrinth::Plugin::Hits:
    file:     lib/Labyrinth/Plugin/Hits.pm
    version:  5.06
  Labyrinth::Plugin::Images:
    file:     lib/Labyrinth/Plugin/Images.pm
    version:  5.06
  Labyrinth::Plugin::Inbox:
    file:     lib/Labyrinth/Plugin/Inbox.pm
    version:  5.06
  Labyrinth::Plugin::Menus:
    file:     lib/Labyrinth/Plugin/Menus.pm
    version:  5.06
  Labyrinth::Plugin::News:
    file:     lib/Labyrinth/Plugin/News.pm
    version:  5.06
  Labyrinth::Plugin::Users:
    file:     lib/Labyrinth/Plugin/Users.pm
    version:  5.06
  Labyrinth::Plugin::Users::Info:
    file:     lib/Labyrinth/Plugin/Users/Info.pm
    version:  5.06

no_index:
  directory:
    - t

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Core

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
